inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3 # adapte en fonction de ta version Ruby
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
