# .solargraph.yml

include:
  - "**/*.rb"
  - "**/*.rake"
exclude:
  - "log/**/*"
  - "tmp/**/*"
  - "vendor/**/*"
  - "node_modules/**/*"
  - "db/schema.rb"

require:
  - rails
  - active_record
  - action_controller
  - action_view
  - action_mailer
  - active_job
  - active_support
  - rake

reporters:
  - rubocop

plugins:
  - rails

completion:
  chain: true

diagnostics: true
